# Generated by Django 4.0.5 on 2022-06-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
    ]
