# Generated by Django 4.0.5 on 2022-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='usernameDefault', max_length=255),
            preserve_default=False,
        ),
    ]
